### ISSUE TITLE
Sikuli-framework does not work on windows

### ISSUE THREAD

**Issue by mandeepsandhu** [smysnk/sikuli-framework#1]
For starters, the `sikuli-script.jar` that's in the repo, seems to be for a Mac/OSX install. This needs to be made dynamic for different platforms.

Even after overwriting it with the correct version of the jar file, it fails in loading some libs. Here's the o/p:

<pre>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0
x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[error] ResourceLoaderBasic: loadLib: Fatal Error 110: loading: WinUtil.dll
[error] ResourceLoaderBasic: loadLib: Since native library was found, it might b
e a problem with needed dependent libraries
C:\Users\mandeep\SikuliX\libs\WinUtil.dll: Can't find dependent libraries
[error] ResourceLoaderBasic: loadLib: Check, wether a valid Sikuli libs folder i
s in system path at runtime!
[error] Terminating SikuliX after a fatal error(110)! Sorry, but it makes no sen
se to continue!
If you do not have any idea about the error cause or solution, run again
with a Debug level of 3. You might paste the output to the Q&A board.
----------------------------
Performing post processing..
----------------------------
Done.
</pre>

**Comment by GielRaijmakers** [comment]
I also get the next error: 
Microsoft Windows [Version 6.3.9600]

D:\Sikuli>runIDE.cmd
+++ running this Java
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) Client VM (build 25.31-b07, mixed mode, sharing)
+++ trying to start Sikuli IDE
+++ using: -Xms64M -Xmx512M -Dfile.encoding=UTF-8 -Dsikuli.FromCommandLine -jar
D:\Sikuli\sikuli-ide.jar
apr 29, 2015 2:08:35 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0
x80000002. Windows RegCreateKeyEx(...) returned error code 5.


Any idea what seems to be the issue??
I tried the windows exe installer, the zipfile and finially the JAR file installer... Can't seem to get it going.
